CPU and Memory overuse when use push and the queue is over 100  or worker over 1k.
bitleak/lmstfy pull request #58
Opened 2020-09-11 10:26 UTC by chensunny

CPU and Memory overuse when use push and the queue is over 100  or worker
over 1k.

✅ Closes: https://github.com/bitleak/lmstfy/issues/56
✅ Closes: https://github.com/bitleak/lmstfy/issues/57

2020-09-11 13:05 UTC, git-hulk requested changes

2020-09-11 13:05 UTC, git-hulk commented on engine/redis/metrics.go
> +	//sv := newSummaryHelper
remove `sv := newSummaryHelper`

2020-09-11 13:05 UTC, git-hulk commented on push/meta.go
> +		return errors.New(fmt.Sprintf("workers should be between 1 and %d",maxWorkerNum))
code tidy =>
`fmt.Errorf("workers should be between 1 and %d", maxWorkerNum)`

2020-09-14 02:25 UTC, liguangbo commented
trvis的go版本应该升级到1.13。time.Milliseconds 是从1.13开始支持的，或者用Nanoseconds()/1e6 来代替。

2020-09-15 05:44 UTC, liguangbo requested changes

2020-09-15 05:44 UTC, liguangbo commented on server/handlers/metrics.go
> +            Buckets:   prometheus.ExponentialBuckets(15, 2.5, 9),
format code

2020-09-15 06:20 UTC, git-hulk approved these changes
LGTM

2020-09-15 07:01 UTC, liguangbo approved these changes

2020-09-15 07:02 UTC, merged